# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - make lint

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    flags:
      - trimpath
    ldflags:
      - -s -w