name: 'Extract Code Blocks from Markdown'
description: 'Extract code blocks from markdown files with filtering'
author: 'ntnn'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  input:
    description: 'Path(s) to the input markdown file(s)'
    required: true
  output:
    description: 'Path to the output file, or "-" for stdout (default: "-", not compatible with multi)'
    required: false
    default: '-'
  multi:
    description: 'Extract inputs to multiple files based on the file tag (default: false, not compatible with output)'
    required: false
    default: 'false'
  tags:
    description: 'Comma-separated tags to filter code blocks'
    required: false
    default: ''
  exclude-tags:
    description: 'Comma-separated tags to exclude code blocks'
    required: false
    default: ''
  exclude-comments:
    description: 'Whether to include code blocks inside HTML comments (default: false)'
    required: false
    default: 'false'

outputs:
  extracted:
    description: 'The extracted code blocks as a string (only when output is "-")'
    value: ${{ steps.extract.outputs.code }}

runs:
  using: 'composite'
  steps:
    - name: Build mdextract
      shell: bash
      run: |
        cd ${{ github.action_path }}
        make build

    - name: Extract code blocks
      id: extract
      shell: bash
      run: |
        out="${{ inputs.output }}"
        if [ "${{ inputs.output }}" = "-" ] && [ "${{ input.multi }}" = "false" ]; then
          out="$(mktemp)"
        fi

        "${{ github.action_path }}/bin/mdextract" \
          -output="$out" \
          -multi="${{ inputs.multi }}" \
          -tags="${{ inputs.tags }}" \
          -exclude-tags="${{ inputs.exclude-tags }}" \
          -exclude-comments="${{ inputs.exclude-comments }}" \
          ${{ inputs.input }}

        if [ "${{ inputs.output }}" = "-" ] && [ "${{ input.multi }}" = "false" ]; then
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "code<<$EOF" >> $GITHUB_OUTPUT
          cat "$out" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        fi
